### ISSUE TITLE
Изменение данных по ссылке

### ISSUE THREAD

**Issue by schn27** [locodiosa/advent-of-code2016#17]
https://github.com/locodiosa/advent-of-code2016/blob/38582dcd2e23f9a94ca87f140bb40e7411f487b4/adventofcode11.html#L78

newNextFloor является ссылкой на этаж (а не копией этажа), а значит последующие операции должны будут изменить состояние этажа до окончания проверки валидности изменений.

**Comment by locodiosa** [comment]
исправлено
